### ISSUE TITLE
Getting started and CMake integration example errors

### ISSUE THREAD

**Issue by GabrielMoreiraSilva** [ImJimmi/JIVE#126]
### On the README.md file, the section Integration/CMake should include:

```
target_compile_definitions(my_juce_project
PRIVATE
    JIVE_GUI_ITEMS_HAVE_STYLE_SHEETS=1
)
```
Spent 1 hour trying to figure out why the "style" property used on "Getting Started" wouldn't work 😭 

### Typo on docs/Getting Started.md:

```
class WindowPresenter
{
public:
    WindowPresenter()
        : view{ views::window() }
    {
    }

    juce::ValueTree preset() <----- It should be "present"
    {
        return view;
    }

private:
    juce::ValueTree view;
};
```

**Comment by ImJimmi** [comment]
Thanks for reporting, and apologies for the time wasted!

I've added your suggested changes here: https://github.com/ImJimmi/JIVE/pull/127
