### ISSUE TITLE
error in git clone git@github.com:ImJimmi/JIVE.git and issue with juce::ValueTree get and release?

### ISSUE THREAD

**Issue by mightgoyardstill** [ImJimmi/JIVE#135]
hey, just trying to get setup following your guides.. ran into an issue when trying to clone the repo

```git clone git@github.com:ImJimmi/JIVE.git
Cloning into 'JIVE'...
The authenticity of host 'github.com (140.82.121.3)' can't be established.
ECDSA key fingerprint is SHA256:p2QAMXNIC1TJYWeIOttrVc98/R1BUFWu3/LiyKgUfQM.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'github.com,140.82.121.3' (ECDSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

so i just went ahead and did ``` git clone https://github.com/ImJimmi/JIVE.git ``` which seemed to work fine

not sure if related now but when i follow along your getting started guide for the plugin editor i get an error saying view (the value tree) has no get or release methods?

**Comment by ImJimmi** [comment]
```bash
git clone git@github.com:ImJimmi/JIVE.git
```

Will clone using SSH, which is recommended but will require generating keys and whatnot. See https://docs.github.com/en/authentication/connecting-to-github-with-ssh.

Cloning with HTTPS is fine if you don't want to use SSH.

> not sure if related now but when i follow along your getting started guide for the plugin editor i get an error saying view (the value tree) has no get or release methods?

Ahh yes sorry that's a typo in the example code - it should be `editor.get()` and `editor.release()`. I'll fix that

**Comment by mightgoyardstill** [comment]
thanks! I figured in the end but thought it was worth keeping this up :)
